### ISSUE TITLE
Setup bundling and minification

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#139]
https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1&tabs=visual-studio

**Comment by anaximander23** [comment]
I might end up taking care of this as a side-effect. The tag input that I want to use is distributed as an npm module, which means that the cleanest way to add it is to add npm and webpack to the project, which will take care of bundling, minification, and a whole bunch of other stuff too. Not sure how long it'll take me; it's been a while since I've had to do this, and it seems to change regularly.
