### ISSUE TITLE
New search page integration stuff

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#152]
@anaximander23 Tracking minor things we (I can tackle all of these probably unless something jumps out to you) should look at as I look at integrating this.

- [x] Icon font no longer working.
- [x] Searching for tags then removing all tags and clicking search still keeps the previous tags.
- [x] General styling
- [x] Re-add source icons
- [x] Add a list of "top" tags
- [ ] Dynamically grow the text area as tags are added
- [x] Telemetry on searches
- [x] Smallest breakpoint should shift the search to the top
- [x] Adding and removing tags from Minis isn't working.
- [x] fix mobile width
- [x] get tooltips working on mobile

**Comment by anaximander23** [comment]
The thing about not removing tags properly will just be an oversight in `tags-tagify.js` somewhere. It might be that instead of what's happening in `onFormSubmitted()`, it would be better to attach to the `add` and `remove` events and keep `tagsValue` in sync that way. I felt like that was mildly hacky anyway.

**Comment by aluhrs13** [comment]
![image](https://user-images.githubusercontent.com/3189095/75950034-f514ba80-5e5c-11ea-9f26-094b7e007a8b.png)

Styling pretty much there :)
